spring:
  profiles:
    active: test
  application:
    name: sso
  datasource:
    name: mysql
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
    url: jdbc:mysql://localhost:3306/arch_data_sso
    username: root
    password: root
server:
  port: 8001

mybatis-plus:
  mapper-locations: classpath*:/mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: top.yangcc.sso
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn


logging:
  level:
    root: info
